version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    volumes:
      - ./src:/home/appuser/app
